	SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
	DROP TABLE apartamento;
	SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

	SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
	DROP TABLE condominio_mensalidade;
	SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
	
	SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
	DROP TABLE condominio_usuario;
	SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

	SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
	DROP TABLE condominio;
	SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;


	SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
	DROP TABLE convidado;
	SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

	SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
	DROP TABLE endereco;
	SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

	SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
	DROP TABLE indisponibilidade;
	SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

	SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
	DROP TABLE mensalidade;
	SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

	SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
	DROP TABLE papel;
	SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
	
	SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
	DROP TABLE reserva;
	SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

	SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
	DROP TABLE usuario;
	SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

	SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
	DROP TABLE usuario_papel;
	SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

	SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
	DROP TABLE boleto;
	SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

	SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
	DROP TABLE convite;
	SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;	

	SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
	DROP TABLE tipo_reserva;
	SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;	
	
	SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
	DROP TABLE recurso_tipo_reserva;
	SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;	
	
	SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
	DROP TABLE condominio_convite;
	SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;	
	
	SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
	DROP TABLE imagem;
	SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;	
	
	SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
	DROP TABLE recurso;
	SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;